version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: medical_checkup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  meilisearch:
    image: getmeili/meilisearch:v1.8
    environment:
      MEILI_MASTER_KEY: masterKey
      MEILI_NO_ANALYTICS: 'true'
    ports:
      - '7700:7700'
    volumes:
      - meilidata:/meili_data

volumes:
  pgdata:
  meilidata: