version: '3.8'
services:
  nextjs:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/medical_checkup
      MEILISEARCH_HOST: http://meilisearch:7700
      MEILISEARCH_API_KEY: masterKey

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: medical_checkup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  meilisearch:
    image: getmeili/meilisearch:v1.8
    environment:
      MEILI_MASTER_KEY: masterKey
      MEILI_NO_ANALYTICS: 'true'
    ports:
      - '7700:7700'
    volumes:
      - meilidata:/meili_data

volumes:
  pgdata:
  meilidata: